### PR TITLE
Username and password login

### PR DESCRIPTION
**Pull request by SaHHiiLL**
# What have I added?
I have added few new classes in java. 

`KeyHandler.java`
`KeyHttpRequest.java`
`KeyModel.java`
`ExistingKeyModel.java`

## KeyHttpRequest.java
This class will make the http requests. Right now every method calls `login()` to get the cookie manager object, which is required. This slows the application down when it has to wait for all `login` calls. I need some suggestions as how should I make this better. my initial though is to make a static refrence of `HttpClient.Builder` and check in every method is the static refrense is null, and give it a value if it is.  But i have some doubts such as, wouldn't cookie expire when in 40mins? and the object will not be null this could create chaos when multiple `ClashApi` object are referencing the same static value.

## KeyModel
Class to represent the json response from the clash when it creates a new token

## ExistingKeyModel
Class to represent the json response from the clash when it returns an existing token

## KeyHandler.java
As the name suggests this class handles all the incomming json responses from `KeyHttpRequest.java`, which is then mapped to a POJO to either `ExistingKeyModel` or `KeyModel`. 

## Miscellaneous
- Would need **java 11**, as `HttpClient` is not available in lower versions of java
- I also recommend making all the endpoint methods __async__ with `CompletableFuture` class

### CODE REVIEW

**Review by jasonlessenich — COMMENTED** [review]
May I ask why you put the whole file path in there lol

**Comment by jasonlessenich** [comment]
@Lycoon Is this still maintained?

**Comment by SaHHiiLL** [comment]
@DynxstyGIT what file path are you talking about? `.gitignore`

**Comment by jasonlessenich** [comment]
> @DynxstyGIT what file path are you talking about? `.gitignore`

yup

**Comment by SaHHiiLL** [comment]
> > @DynxstyGIT what file path are you talking about? `.gitignore`
> 
> yup

eh, not really sure tbh. Probably did that in hurry. But ty for pointing it out. I have removed it :D

**Comment by SaHHiiLL** [comment]
This commit introduces a new feature to login via multiple Api accounts and the ability to rotate the keys for all the accounts. 

- Firstly we have a new Class called mutexList, its only job is to cycle through the list of keys (Strings) and rotate then whenever a request is made. This is done to avoid hitting a 429 status code.  

- Another new class is introduced called `Credentials` which is just a abstraction for the email and password.

- KeyHandler class is also modified to and optimised - not really that import nothing has changed for the most part. 

- In `ClashAPI.kt` I have added several method which are annotated with synchronised to prevent data race. and have created a new constructor for bulk login.  

## Limitation
It takes roughly about 60ish seconds to request about 10,000 tag (10,000 API requests) with this implementation

```java
public static void main(String[] args) {
        List<Credentials> credentials = List.of(
                new Credentials("email", "password"),
                new Credentials("email", "password"),
                new Credentials("email", "password")
        );
        ClashAPI c = new ClashAPI(credentials);

        for (int i = 0; i < 10000; i++) {
            int finalI = i;
            
            new Thread(() -> {
                Clan clan = null;
                try {
                    clan = c.getClan("#r8j");
                } catch (ClashAPIException e) {
                    e.printStackTrace();
                   
                }catch (IOException e){
                    e.printStackTrace();
                }
                System.out.println(clan.getName() + " " + finalI);
            }).start();
        }
        while(true){}
    }
````
The more accounts you have, lower the chance of you hitting RateLimit. BUT this operation is extremely memory heavy and Network heavy. Additionally requesting this many tags may highly dependent on the system whether it will throw an exception or not.  Even by just requesting 1000 tags I was getting all sort of IO and Sockets exceptions, thou this may be me using the thread class instead of a better implementation for multi threading.

**Comment by SaHHiiLL** [comment]
After some research I modified the test code to this. 
```java
public static void main(String[] args) throws ExecutionException, InterruptedException {
        List<Credentials> credentials = List.of(
                new Credentials("email", "password"),
                new Credentials("email", "password"),
                new Credentials("email",  "password"),
                new Credentials("email",  "password"),
        );
        ClashAPI c = new ClashAPI(credentials);

        List<Future<?>> futures = new ArrayList<>();
        ExecutorService service = Executors.newFixedThreadPool(500);
        long start = System.currentTimeMillis();
        for (int i = 0; i < 100_000; i++) {
            int finalI = i;
            Runnable runnable = () -> {
                try {
                    Clan clan = c.getClan("#r8j");
                    System.out.println(clan.getName() + " " + finalI);
                } catch (ClashAPIException e) {
                    e.printStackTrace();
                    System.exit(1);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            };
            futures.add(service.submit(runnable));
        }

        for (Future<?> future : futures) {
            while (!future.isDone()){}
        }
        long stop = System.currentTimeMillis();
        System.out.println("DONE");
        System.out.println("Calculated in: " + (stop - start) / 1000 + " seconds" );
    }
```

I was able to fetch around all 100k requests in 60ish seconds. - I believe 40 tokens is more then enough for this use case. anymore are redundant.

**Comment by SaHHiiLL** [comment]
Closing this pr as there's no response from the maintainer for months.

**Pull request closed without merging**
